language: python
os: linux
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev

install:
  - pip install flake8 pytest pytest-doctestplus

script:
  - set -e
  - flake8 .
  - python -We:invalid -We::SyntaxWarning -m compileall -f -q removestar/
  - pytest
  # Make sure it installs
  - python setup.py install
